### ISSUE TITLE
Accessing a locale initializes it

### ISSUE THREAD

**Issue by pwim** [shioyama/mobility#100]
I noticed when I access a given locale with the table backend, a Translation object is also getting initialized. This means I have two translation records for every object I create.

More specifically, I have an `Event` class like the following.

``` ruby
class Event < ApplicationRecord
  translates :title, backend: :table
  validates :title_en, length: { maximum: 255 }
  validates :title_ja, length: { maximum: 255 }
end
```
Because I have two validations on the length (maybe there's a better way to do this with mobility?), whenever I create an event, I get two translation records. This behavior doesn't appear to be specific to accessing it within the validation context. If I remove those validations, the following spec still fails.

``` ruby
it do
  event = Event.new(title: "MyTitle")
  expect(event.translations.pluck(:title)).to eq([event.title])
  event.title(locale: :ja)
  event.save!

  # will fail with ["MyTitle", nil]
  expect(event.translations.pluck(:title)).to eq([event.title])
end
```

The plugins don't seem to effect this. Even with the default options, it still happens. Is this behavior intentional?

**Comment by shioyama** [comment]
Hmm... no this is not intentional. Actually in the KeyValue backend there's a `before_save` callback that [destroys any blank translations](https://github.com/shioyama/mobility/blob/e803847f967117a34ef8f31491af555836d97c6d/lib/mobility/backends/active_record/key_value.rb#L66-L70), maybe the Table backend needs something like this.

The reason this happens is [this line](https://github.com/shioyama/mobility/blob/e803847f967117a34ef8f31491af555836d97c6d/lib/mobility/backends/active_record/key_value.rb#L91), where the translation is built if it is currently missing. The similar line in Globalize is [here](https://github.com/globalize/globalize/blob/342a457548ce358f6fe5f7f5fdfeaae61560ccd2/lib/globalize/active_record/instance_methods.rb#L116).

The problem is that whereas the KeyValue backend can easily destroy blank translations, in the case of the table backend you'd need to check that all attributes on the translation record are blank before destroying it (since unlike KeyValue it holds one or more translated columns). So perhaps slightly more tricky, not sure about performance implications.

**Comment by shioyama** [comment]
This is more of an oversight, but labelling it as a bug. Thanks for pointing it out!

**Comment by shioyama** [comment]
Btw, for the validator, you can use the `locales` method on the backend (or `each_locale` to yield each locale to a block) to get all present locales, and use that in a custom validator to just validate the locales for which there are actually translations. This will avoid creating new ones when validating.
