### ISSUE TITLE
n+1 calls when retrieving all records of a model

### ISSUE THREAD

**Issue by Dion-clarity** [shioyama/mobility#105]
One problem I have with the Moblity Gem is that when I wanted to display the translated attributes of all records, a separate call is made to the database for each record
(OR maybe I don't know how to do it correctly; if this is the case, please let me know)

I tried writing a helper method myself, which can be found here:
http://railsmisadventures.blogspot.hk/2017/10/eliminate-n1-calls-using-mobility-gem.html

But I would certainly like this incorporated into the gem itself in someway to make things simpler

**Comment by shioyama** [comment]
Thanks, I'll have a look, but just to clarify this is *for the KeyValue backend specifically*. Because it's polymorphic querying is quite tricky...

**Comment by shioyama** [comment]
So I've finally taken some time to think about this problem a bit, and I think there is a simple way to solve the N+1 problem without any code changes.

You can simply use `eager_load(:text_translations)` (or `eager_load(:string_translations)` if the key-value attribute is a string) to tell AR to eager-load the association. Everything else works the same.

e.g. if I have a model `Post` with an attribute `title`, like this:

```ruby
class Post < ApplicationRecord
  extend Mobility
  translates :title, backend: :key_value
end
```

Then I can eager load the translated attribute like this:

```ruby
posts = Post.i18n.where(title: "foo").eager_load(:text_translations)
```

If you then iterate through the results, you should not see any extra queries, since they have already been eager-loaded.

The SQL becomes:

```
SELECT "posts"."id" AS t0_r0, "posts"."created_at" AS t0_r1, "posts"."updated_at" AS t0_r2,
  "text_translations_posts"."id" AS t1_r0,
  "text_translations_posts"."locale" AS t1_r1,
  "text_translations_posts"."key" AS t1_r2,
  "text_translations_posts"."value" AS t1_r3,
  "text_translations_posts"."translatable_id" AS t1_r4,
  "text_translations_posts"."translatable_type" AS t1_r5,
  "text_translations_posts"."created_at" AS t1_r6,
  "text_translations_posts"."updated_at" AS t1_r7 FROM "posts"
LEFT OUTER JOIN "mobility_text_translations" "text_translations_posts"
  ON "text_translations_posts"."translatable_id" = "posts"."id"
  AND "text_translations_posts"."key" = 'title'
  AND "text_translations_posts"."translatable_type" = $1
INNER JOIN "mobility_text_translations" "title_text_translations"
  ON "title_text_translations"."key" = 'title'
  AND "title_text_translations"."locale" = 'en'
  AND "title_text_translations"."translatable_type" = 'Post'
  AND "title_text_translations"."translatable_id" = "posts"."id"
WHERE "title_text_translations"."value" = $2  [["translatable_type", "Post"], ["value", "foo"]]
```

What is actually happening is that AR is doing *two* aliased joins now, one an `INNER JOIN` that Mobility has added to find matching posts that match the condition on title, and an `OUTER JOIN` that is triggered by the `eager_load`, which loads all columns on the `mobility_text_translations` table for the resulting posts. When you cycle through results now, you should not see any extra queries since they have been loaded with the second (eager load) join.

Can you give this a try and see what you think? I'll make a note of it in the wiki and link from the readme.

I suppose if this is a popular thing, Mobility could make it easier to do eager loading for this backend, so that you could just automatically eager load the associations which make sense. But for now I'd just like to see if this works well, please let me know what you think.

I'll close this once I update the wiki/readme.

**Comment by shioyama** [comment]
Ok, added some detail to the wiki [here](https://github.com/shioyama/mobility/wiki/KeyValue-Backend#eager-loading). I'm closing this, if this looks good let me know and I will add a note to the readme as well.
