### ISSUE TITLE
Create new record with locale accessors (using with friendly_id)

### ISSUE THREAD

**Issue by mcmegavolt** [shioyama/mobility#151]
I have a problem with creating an record using locale accessors in my form inputs:

```ruby
class Category < ApplicationRecord
  extend Mobility
  translates :name, type: :string, locale_accessors: true
  translates :slug

  extend FriendlyId
  friendly_id :name, use: %i[mobility finders]

  validates_presence_of :name_en, :name_ru, :name_uk
end
```

My ActiveAdmin form:

```ruby
form do |_f|
    inputs do
      input :name_ru
      input :name_uk
      input :name_en
    end
    actions
  end
```

When I try to create:

```
SQLite3::SQLException: no such column: categories.slug: SELECT 1 AS one FROM "categories" WHERE ("categories"."id" IS NOT NULL) AND "categories"."slug" = ? LIMIT ?
```

I need to create category records with translations...

**Comment by mcmegavolt** [comment]
So, I've found that if remove *:finders* from **friendly_id use** it works as expected

**Comment by shioyama** [comment]
I don't think Mobility is compatible with finders, since finders assumes you have a `slug` column. I just ran specs now on that gem with `finders` enabled and specs fail... this might be worth mentioning on the friendly_id-mobility github page.

I'm closing this since in any case, it's not an issue of Mobility itself.
