### ISSUE TITLE
friendly_id support 

### ISSUE THREAD

**Issue by stevenwoudstra** [shioyama/mobility#19]
Is there a way to make mobility work with the [friendly_id](https://github.com/norman/friendly_id) gem?
I did got it working with the globalize gem, but it seems not to be working with mobility

**Comment by shioyama** [comment]
It's not on the [roadmap](https://github.com/shioyama/mobility/wiki/Roadmap) currently, so no plans to integrate it.

I would consider it, but FriendlyId does not appear to be currently maintained. Right?

**Comment by stevenwoudstra** [comment]
The last changes were 2 months ago but i don't know of a better alternative yet.

**Comment by shioyama** [comment]
Hmm ok, I saw the last commit dated Sep 2016, but you're right there's been action since then merging some commits.

Still, it's not very high priority TBH. If someone wants to give it a go, I could help with issues on the Mobility side. But my experience with Globalize makes me very hesitant to maintain gems with complex dependencies, and AR + (half-maintained) FriendlyId seems a bit risky to me.

**Comment by shioyama** [comment]
Closing, if there is more interest in this I could re-open it.

**Comment by Rwobbema** [comment]
Support for Friendly ID would be great!

**Comment by shioyama** [comment]
Done: https://github.com/shioyama/friendly_id-mobility
Gem: https://rubygems.org/gems/friendly_id-mobility

*very* lightly tested. Needs some specs. Please try it out and report back, it has only a few lines of code (that's all it seem Mobility needed to work, but I haven' tested it much).

**Comment by shioyama** [comment]
Ok, I just released 0.2.0, which now includes slightly more than the first version. I've added tests to ensure that it should work as expected, both with untransalted base attribute (like the SimpleI18n module included by default with FriendlyId) and translated base attribute (like Globalize). Also, the integration supports any Mobility backend since it only depends on the common interface (so you could e.g. use it with jsonb-translated attributes, etc.)

I'm closing this since it's done :smile: If you see issues with the gem please post issues [over there](https://github.com/shioyama/friendly_id-mobility/).

**Comment by stevenwoudstra** [comment]
Okee i will go and test it on monday.

Thanks a lot ^^

**Comment by shioyama** [comment]
@stevenwoudstra I realized that actually FriendlyId is a nice first extension for Mobility, since it's quite simple to do and a lot of people use it :smile: Thanks for the suggestion.

**Comment by stevenwoudstra** [comment]
I implemented the new gem yesterday and it is working like a charm thanks a lot ^^

**Comment by shioyama** [comment]
Great to hear!
