### ISSUE TITLE
Allowing search for the Key-Value backend (or workaround)

### ISSUE THREAD

**Issue by damienlethiec** [shioyama/mobility#208]
Hi there,

Thanks a lot for the amazing work with the gem.

I know Mobility is doing a lot of custom queries to allow us to find in our translations but this prevent us from doing some proper search, either with SQL or a gem.

I am using the key-value backend and would like to be able to do something like this `Product.where("name ILIKE ?", '%Something%')`, or even better, to be able to use a search gem like pg_search or searchkick.

It is a planned feature? Do you have a workaround? Do you know a search gem that is compatible with Mobility?

Thanks a ton in advance!!

**Comment by shioyama** [comment]
Hey, thanks for your comment.

> I know Mobility is doing a lot of custom queries to allow us to find in our translations but this prevent us from doing some proper search, either with SQL or a gem.

Not really. Mobility helps you with custom queries (with the `i18n` scope) but you can also do normal queries. But then you need to deal with the database structure, which for KeyValue is complicated.

> I am using the key-value backend and would like to be able to do something like this `Product.where("name ILIKE ?", '%Something%')`, or even better, to be able to use a search gem like pg_search or searchkick.

String queries are more or less impossible, I'm afraid. It's much too hard to do magic on them.

It *might* be possible to do some magic with Arel to support things like `LIKE`, but it wouldn't be easy and I haven't had time to really think about it carefully.

Compatibility with other gems is limited to what Mobility offers, which currently is simple `where` queries on hash values (not strings).

In this case, if you want to do queries with `ILIKE`, you'll have to look at how Mobility does queries and adapt some SQL (or Arel) to do what you want. The [KeyValue wiki page's section on querying](https://github.com/shioyama/mobility/wiki/KeyValue-Backend#querying) might be of help here.

**Comment by damienlethiec** [comment]
Hi @shioyama  :)

Thanks for the answers, really helpful!

Last questions: would changing the backend for the specific attributes make it easier to do the search (or the make it "gem compatible")? What would be the best backend for an attribute I need to search? Are there some downsides I should be aware of if I combine the key-value backend for most of my attributes and another backend for the attribute I need to search?

Thanks a ton again :)

**Comment by shioyama** [comment]
> Last questions: would changing the backend for the specific attributes make it easier to do the search (or the make it "gem compatible")?

This is a good question, probably I should write more about this.

The answer is yes: if searching with things like `LIKE` or `LOWER` is important to you, then KeyValue might not be the best backend. KeyValue uses polymorphic relationships which are known to be complicated to query on.

> What would be the best backend for an attribute I need to search?

The easiest for searching would be the Column backend, because in this case you're just searching on simple columns (`title_en`, `title_fr`, etc.). This one should also be the most "gem-compatible" since you would just need to tell the gem to search for e.g. "title_<locale>" instead of "title" and things should work.

But do you want to support many languages? If so you will have many columns on your models, one for each language. Also you will need many more migrations than KeyValue.

The Table backend is a bit more complicated since it still involves joins (you join translation tables), but it scales better with locales, so if you plan to support many languages this one might be better. But gem compatibility would require more work.

If you're using PostgreSQL as your database, then json/jsonb backends, or the new container backend, might be interesting. But they won't be as easy with gem compatiblity, I suppose.

> Are there some downsides I should be aware of if I combine the key-value backend for most of my attributes and another backend for the attribute I need to search?

Mobility supports using more than one backend together, even on the same model, so I don't know of any downsides other than that your data will be more complex (but Mobility doesn't care about this).

For more info on backends, have a look at [this blog post](https://dejimata.com/2017/3/3/translating-with-mobility), and also [this post on JSON translations](https://dejimata.com/2018/3/20/jsonify-your-ruby-translations) if you're using PostgreSQL.

**Comment by damienlethiec** [comment]
Amazing! Thanks!

I will give a try next week to the column backend for the specific attribute in need to query. For the moment I have only 2 locales (I was mainly using key-value to avoid migrations) and I could probably have up to 5 in the end. So it will still be manageable.

I will try to use the pg-search gem with the column backend and will let you know how it goes. It could help you to document the subject!

Thanks a ton again, you don't imagine how reassuring and encouraging it is when you begin to use a new gem to see that the main contributor is so helpful. I will recommend the gem to my friends :D

**Comment by shioyama** [comment]
Sounds good! :+1: 

> Thanks a ton again, you don't imagine how reassuring and encouraging it is when you begin to use a new gem to see that the main contributor is so helpful. I will recommend the gem to my friends :dagger: 

Thanks! :smile:

**Comment by damienlethiec** [comment]
The column backend works perfectly for my use case. I was able to use PG Search without the smallest problem. Perfect solution! Thanks @shioyama !!

**Comment by damienlethiec** [comment]
Awesome! I will unfortunately not have time to help until September but if you need a hand after this, I could maybe to try to help :)

Thanks again :)
