### ISSUE TITLE
how to use multi-search pg_search with mobility?

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [shioyama/mobility#234]
I try to use multi-search pg_search with Mobility. But in this case only last translation of model data save to PgSearchDocuments table.

**Comment by shioyama** [comment]
pg_search has been mentioned before here, but unfortunately I haven't had time to look into it. I suppose it would require some work, maybe a separate gem to integrate Mobility with it. It's not super high priority right now, but if someone wants to try making the integration I can provide support from the mobility side.

I've labelled this as "compatibility", but for now I'm going to close since it's not something I can realistically get to myself anytime soon.

**Comment by shioyama** [comment]
Thanks for the issue of course! Don't be discouraged, but I only leave issues open if I feel I can actually address them in a realistic timespan.
