### ISSUE TITLE
specs fail when running against master but not release branch

### ISSUE THREAD

**Issue by pwim** [shioyama/mobility#345]
As I was mentioned in #343, I went to try running that branch against my Rails application. After updating my Gemfile to reference that branch, my specs failed as mobility wasn't defining `locale_accessors`. 

However, this issue appears to be unrelated to the change, as it also failed when I ran against 119a1aa25932750fef3ddd33ef1bf661b695245f (the release commit for 0.8.8). I'm using the released 0.8.8 in my application without issue, and I confirmed that if I specify the v0.8.8 tag, my specs also pass, so it isn't an issue with using the git reference in my Gemfile.

I went back as far as 41b6fe2373234431ffe83ca0953a9227742b3880, and the specs of my application also failed in the same way.

I guess master and the 0-8-stable branch have diverged for quite some time now. Is there some change to how I need to configure using locale accessors? I'm currently doing it through 

``` ruby
Mobility.configure do |config|
  config.default_options[:locale_accessors] = true
end
```

**Comment by shioyama** [comment]
Ah yeah, `master` has some breaking changes in it which I intend to document before releasing v1.0. Sorry I'm trying to rebase the change against the 0-8-stable branch right now and having some issues, give me some time to get another PR up for that and you can run specs against that one.

Once this dirty plugin issue is fixed, I'll go back to cleaning up master. I pushed a bit too fast before I was ready to commit to release... and now the branches are quite far apart.

**Comment by shioyama** [comment]
Ok #347 should do it. It's getting nasty... I did a bunch of cleanup on master that I'm not really ready to release yet, but it affects specs and makes it hard to cherry-pick. Hopefully this will be the last version on the 0.8 line.

**Comment by shioyama** [comment]
Lesson for me: if you're going to make big changes, be prepared to follow through asap...

**Comment by pwim** [comment]
Got it, thanks for the clarification.

**Comment by shioyama** [comment]
So now that Rails 6 stuff is done, finally had time to catch up at where `master` is at. I made some changes in late 2018 toward a v1.0 release but didn't end up following through at the time. Coming back to it now after nearly a year-long gap.

The basic thing I'm trying to fix for v1.0 is the configuration, which I find really ugly right now. I'm following the example of [Shrine](https://github.com/shrinerb/shrine), which I think does this very nicely. Essentially in Shrine, the `Shrine` constant is a class which you subclass to define an "uploader", and anything you want to configure you do by calling methods on this subclass.

So like this:

```ruby
class ImageUploader < Shrine
  plugin :derivation_endpoint,
    secret_key: "<YOUR SECRET KEY>",
    prefix:     "derivations/image" # needs to match the mount point in routes 
 
  derivation :thumbnail do |file, width, height|
    ImageProcessing::MiniMagick
      .source(file)
      .resize_to_limit!(width.to_i, height.to_i)
  end
end
```

This is nice since it means you don't have stuff like "default_options" and "options", with one being merged into the other. Instead, you just use inheritance to customize whatever you want on the subclass. This also means you can define multiple uploaders, re-use configuration between them, etc simply using class inheritance. By calling `plugin` on `Shrine` itself, you enable the plugin globally (since all uploaders descend from that class).

In Mobility, the corresponding class would be `Mobility::Attributes`, and my idea is that you would do something like this:

```ruby
class TranslatedAttributes < Mobility::Attributes
  plugin :dirty
  plugin :locale_accessors, locale_accessors: [:en, :ja]
  plugin :fallbacks, fallbacks: { en: :ja, ja: :en }
  # ...
end

class Article < ActiveRecord::Base
  include TranslatedAttributes.new(:title, :content)
end
```

I'm not quite sure about the API yet, but the key thing here is that you can have cascading defaults through inheritance, so you could (e.g.) have one set of fallbacks, then for a subset of models a more refined set, etc. Since it's all done through inheritance, the code in Mobility would not be any more complex (in fact it should be simpler).

The challenge is to make this backwards compatible to the current configuration API, but I think I can do that. I don't want people to *have* to include an instance of a class (`include TranslatedAttributes.new(:title, :content)`) because I think this can be quite intimidating for newcomers; it should be available but there should also be a simple macro (`translates`) which does the same thing under the hood.

**Comment by shioyama** [comment]
That said, looking at the code, I'm not quite sure why `default_options` isn't working on master. It seems like it should still be supported. I'll try to write a failing spec for it.

**Comment by shioyama** [comment]
Ah never mind, I see the problem. `default_options` is used when creating an instance of `Mobility.attributes_class`, but the plugin itself is not enabled.

This will work on `master` (in the Mobility initializer):

```diff
Mobility.configure do |config|
  # ...

+ config.attributes_class.plugin :locale_accessors
+ # same for any other plugins you use

  config.default_options[:locale_accessors] = true
  # ...
end
```

But I don't want this to actually be the required interface, so consider this a WIP.
