### ISSUE TITLE
attribute_present? doesn't work as anticipated

### ISSUE THREAD

**Issue by pwim** [shioyama/mobility#355]
I happened to notice that [`attribute_present?`](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods.html#method-i-attribute_present-3F) appears to always return false.

**Comment by shioyama** [comment]
Yeah, I don't think it ever worked, did it? The problem is that to get these methods to work requires patching each one. Declaring attributes using the attributes API doesn't work since they are not simple stored values but mappings.

I don't want to add lots of overrides to the core, but I'd consider putting them in a plugin or something, You could try the `attribute_methods` plugin, which adds attributes to the `attributes` hash, but I suspect that won't work since the coupling is deeper in more recent versions of AR/AM.

**Comment by shioyama** [comment]
I guess part of the problem is that I'm hesitating about where to draw the line. For now, the `dirty` plugin tries to patch all methods that you would expect to work, but `attribute_present?` is not part of dirty so it's not patched in there.

**Comment by pwim** [comment]
I came across this as part of a debugging session in the console. I'm not actually trying to take advantage of it in my code, so I can personally live without it. It just took me a minute to realize the attribute I was passing to it was a mobility one, which is why it wasn't working as anticipated. Sounds like it is fine to close as a wontfix then.

**Comment by shioyama** [comment]
> It just took me a minute to realize the attribute I was passing to it was a mobility one

This is both Mobility's strength and it's weak spot. Translated attributes *almost* act like normal attributes, especially if you add the dirty plugin, but there will always be limits. I find myself having to explain this time and time again, and I can understand why -- in my own experience using Mobility I come ot expect the same thing.

Anyway thanks for closing, I might add a wiki page or something explaining the differences and what Mobility does and does not do.
