### ISSUE TITLE
Fallbacks are filling in empty fields in forms

### ISSUE THREAD

**Issue by Rwobbema** [shioyama/mobility#40]
I can't figure out how I correctly setup a form when using fallbacks. Now all the empty fields are filled in by the fallback language.

**Comment by shioyama** [comment]
There is a `fallback` option which you can pass to an accessor to disable fallbacks, like this:

```ruby
post.title(fallback: false)
#=> returns the actual value of the title, in the current locale, or nil if it is nil
```

So in your form, if you just pass `value: @post.title(fallback: false)` etc for every form field, you should get the actual values rather than the fallback value. So something like this:

```ruby
post.text_field :title, value: post.title(fallback: false)
```

That's a bit repeatitive, so you might want to do something with a form object to send `fallback: false` to all attributes. I haven't looked to deeply at it but something should be possible; otherwise the solution above should work.

**Comment by shioyama** [comment]
For more detail on fallbacks, see the [API docs](http://www.rubydoc.info/gems/mobility/Mobility/Backend/Fallbacks).

**Comment by shioyama** [comment]
Just playing around a bit with form builders, I found this works:

```ruby
class FormBuilderWithFallbacksDisabled < ActionView::Helpers::FormBuilder
  %w[text_field text_area].each do |field_name|
    define_method field_name do |attribute, options={}|
      super(attribute, options.merge(value: @object.send(attribute, fallback: false)))
    end
  end
end
```

You use it like this:

```ruby
<%= form_for @post, builder: FormBuidlerWithFallbacksDisabled do |f| %>

  ...
  <%= f.label :title %>:
  <%= f.text_field :title %><br />
  ...

  <%= f.submit %>
<% end %>
```

`text_field`s and `text_areas` will not show fallback values. If you want to include all fields, just add to the array `%w[...]` in the `FormBuilderWithFallbacksDisabled` class above.

**Comment by shioyama** [comment]
I added a section to the wiki on this topic: https://github.com/shioyama/mobility/wiki/Using-Mobility-with-Forms

I added a bit to the form builder above to make it handle both translated and untranslated attributes.

I'm closing this issue since I consider it resolved. Let me know if you encounter any further issues.
