### ISSUE TITLE
Initializer test is missing

### ISSUE THREAD

**Issue by sedubois** [shioyama/mobility#411]
There is currently no test verifying that the initializer (e.g as it is generated by `rails g mobility:install` is correct.

Ref: https://github.com/shioyama/mobility/issues/410#issuecomment-655535732

**Comment by shioyama** [comment]
Just to clarify (because I understand what you mean but it might not be clear to others), there [is](https://github.com/shioyama/mobility/blob/b24eb429b9b4ecf8cd1c4e7dae47d2e40de4d23e/spec/generators/rails/mobility/install_generator_spec.rb) an install generator spec, the problem is that it doesn't actually _run_ the generator, it just checks that the file it generates matches what the specs test for.

Currently on `master`, the spec passes but actually the install generator does not run correctly. This needs to be fixed but I'm putting it off until I finish cleaning up some other stuff so that everything can change together.
