### ISSUE TITLE
Translating Rails has_many string attribute

### ISSUE THREAD

**Issue by sedubois** [shioyama/mobility#439]
## Context

Considering a Rails 6 application with a `sluggable` polymorphic relation, a model's `has_many` collection of slugs localized to different languages can be modeled as follows:

```rb
# slugs table schema
create_table :slugs do |t|
  t.references :sluggable, polymorphic: true
  t.string :locale, null: false
  t.string :name, null: false
  t.timestamps null: false
end
add_index :slugs, [:locale, :name], unique: true

# app/models/slug.rb
class Slug < ApplicationRecord
  belongs_to :sluggable, polymorphic: true
end

# app/models/post.rb
class Post < ApplicationRecord
  has_many :slugs, -> { where(locale: I18n.locale).order(created_at: :desc) }, as: :sluggable
end
 
# app/models/course.rb
class Course < ApplicationRecord
  has_many :slugs, -> { where(locale: I18n.locale).order(created_at: :desc) }, as: :sluggable
end
```

This should meet the following requirements:

1. A `sluggable` can have a different amount of `slugs` in each language (there isn't a direct mapping between a slug in one language and a slug in another);
2. A constraint ensures the slugs are unique for each locale (`sluggable_type` could be included in the index depending on whether one wishes slugs to be unique across the application or unique within each model type);
3. One single join is required (takes care of both the translation and the slug<->post relationship);
4. The relation keeps its order to allow picking the "default" slug.

A post's slugs can be queried with`post.slugs`. By convention the post's "default" slug would be `post.slugs.first.name`.

A post can be found by its locale and slug with `Post.joins(:slugs).find_by(slugs: { name: "my-slug" })`.

__________

## Expected Behavior

I am looking for an equivalent Mobility implementation which meets the requirements above. I already use Mobility in the rest of my app and would like to be able to query translated content in a consistent manner (same APIs, fallbacks, etc).

## Actual Behavior

I do not know of any way to achieve this with Mobility.

The [key-value backend documentation][1] seems to fit the bill for requirement nr.3, i.e. the `mobility_string_translations` table is a polymorphic relation which looks like it could replace the `slugs` table. However concerning nr.2, it declares a unique index across `["translatable_id", "translatable_type", "locale", "key"]` so it wouldn't allow multiple slugs for a given `sluggable` and locale. The documentation shows how to translate attributes with a single value in each locale (e.g. a `Post` with a `title`), but not with several values (e.g. a `Post` with several slugs, as above). 

Does Mobility support the above scenario, or can/should it be implemented with some kind of new backend?

## Possible Fix

Either the Key-Value backend could receive an option like `has_many: true` or some kind of `HasManyKeyValue` backend could be added?

PS: I also opened [a question on SO](https://stackoverflow.com/questions/63841953/translating-rails-has-many-string-attribute-using-mobility).
PPS: [In this SO question][2] I also considered the possibility of storing these slugs in a JSONB array, but it is [recommended against][3], and besides, Mobility [can only translate `string` and `text` types][4].

  [1]: https://github.com/shioyama/mobility/wiki/KeyValue-Backend
  [2]: https://stackoverflow.com/q/63836371/4623987
  [3]: https://stackoverflow.com/a/63840217/4623987
  [4]: https://github.com/shioyama/mobility/issues/389

**Comment by shioyama** [comment]
Thanks for the detailed description! :heart: I'd like to help, but unfortunately I'm putting all my time into an alpha 1.0 release, so can't follow up on this now.

> Mobility can only translate string and text types.

Let's clarify first that you are referring to the KeyValue backend here. But also, see my comment [here](https://github.com/shioyama/mobility/issues/389#issuecomment-695146555), I want to clarify that _this is not a serious limitation_. The example in the issue you pointed to involved parsing query strings, which Mobility does not support and will not support in the future (nor does any ActiveRecord query gem I know of), because it is much too difficult and error-prone to do so.

However if you want, say, an integer translation type with the KeyValue backend, you just need to create a new class for the translations and make the column an integer type, and everything else should work fine. I'd like to document this, but it's not a huge priority since it's not an often asked-for feature.

Your example was a `jsonb` column on the KeyValue backend, which is a rather unusual setup. Even then, aside from string queries, it should work as well. Mobility tries to make as few assumptions as possible about what you want to do with it.

**Comment by sedubois** [comment]
Thank you @shioyama. The idea of using JSONB could be followed in #389. I would suggest to let this issue focus on the non-JSONB solution, required at least to ensure uniqueness. Anyway I might not progress much with this and might instead just use the custom solution shown above.

**Comment by shioyama** [comment]
Closing this as I don't think it's really actionable.
