### ISSUE TITLE
Add as_json and to_json support.

### ISSUE THREAD

**Issue by ippachi** [shioyama/mobility#465]
## Context
mobility: 0.8.13
rails: 6.0.3.4

I use mobility with rails. And I use `model.as_json` current project. But mobility column doesn't show up.
So I want mobility to support `as_json` and `to_json`.

## Expected Behavior
```ruby
class User < ApplicationRecord
  translates :name
end
User.name = 'username'
User.new.as_json(only: [:name]) # => {name: 'username'}
```

## Actual Behavior
```ruby
class User < ApplicationRecord
  translates :name
end
User.name = 'username'
User.new.as_json(only: [:name]) # => {}
```

## Possible Fix
In my project, I override `attributes` method like below. And it is work.

```ruby
class User < ApplicationRecord
  translates :name

  def attributes
    hash = super
    self.class.translated_attribute_names.each do |name|
      hash[name] = __send__(name)
    end

    hash
  end
end
```

I don't know this solution is good or bad. But I'm afraid this way because this method changes rails core.

**Comment by shioyama** [comment]
You can use the `attribute_methods` plugin for this, it will add translated attributes to the `attributes` hash (basically like you've done). If you're using the latest version of Mobility, you enable it by calling `attribute_methods` in your plugins block:

```ruby
Mobility.configure do
  plugins do
    # ...
    attribute_methods
  end
end
```

This plugin isn't well documented, because it can have unexpected consequences (since Mobility attributes are not "real" attributes).

**Comment by ippachi** [comment]
I try this plugin.
Thank you for your help! 😄
