### ISSUE TITLE
Pass fallback locale in getter

### ISSUE THREAD

**Issue by simonknoll** [shioyama/mobility#5]
Accessing a specific language works already neatly with
`post.title(locale: :en)`
It would be great if one could simply pass a fallback locale in the getter directly
`post.title(locale: :en, fallback: :de)` #

**Comment by shioyama** [comment]
Interesting idea! I'll have a look.

**Comment by simonknoll** [comment]
:+1: thanks for considering!

**Comment by shioyama** [comment]
@simonknoll see #9.

**Comment by simonknoll** [comment]
Thank you so much, this makes my live much easier!

**Comment by shioyama** [comment]
#9 has been merged, closing this.

**Comment by simonknoll** [comment]
@shioyama I tried now with version `0.1.7` but I can't get it working. Maybe I'm using it not as intended. Anyways I've created a simple test project with a [rspec test](https://github.com/simonknoll/mobility-fallback/blob/master/spec/models/contribution_spec.rb). This is the repository https://github.com/simonknoll/mobility-fallback

Cheers,
Simon

**Comment by shioyama** [comment]
@simonknoll I see the problem. You need to enable fallbacks on the model in order to set them in the getter, otherwise the `Mobility::Backend::Fallbacks` module will not be included.

So if you define the `Contribution` model this way, it will work:

```ruby
class Contribution < ApplicationRecord
  include Mobility
  translates :landing_page, type: :string, fallbacks: true
end
```

Note that if you then want somewhere else *not* to use fallbacks for `landing_page`, you'll need to pass `fallback: false`, i.e. `contribution.landing_page(fallback: false)`.

We probably need a way to include the module, but disable it by default. I'm thinking about a natural interface for that...

**Comment by shioyama** [comment]
Actually I'm noticing an issue with 0.1.7 which is causing lots of bogus warnings in the logs. I'll fix it tomorrow and release a new version. (Working on this on [this](https://github.com/shioyama/mobility/tree/fallbacks_super) branch.)

Also, I should be able to change the API so that it includes the fallbacks module by default, but only actually uses it if when `fallback: ...` is passed to the getter. But I want to think about this a bit more before making that change.

**Comment by simonknoll** [comment]
Thank you for the clarification @shioyama!

**Comment by shioyama** [comment]
@simonknoll try version 0.1.10 (had to yank 0.1.8 + 0.1.9...).
