### ISSUE TITLE
Can't translate Rails enums

### ISSUE THREAD

**Issue by sedubois** [shioyama/mobility#519]
## Context
It appears translating a Rails enum attribute with Mobility prevents the enum functionality from working.

## Expected Behavior
Enum attributes can be translated, enum getters and setters work as expected.

## Actual Behavior
Attribute behaves as if no enum was defined for it. E.g for a `foo` attribute with `enum foo: { bar: 1, baz: 2 }`, `obj.foo = 'bar'` doesn't work (assigns 0), querying `obj.foo` returns an integer instead of string, and `obj.bar?` always returns false.

## Possible Fix
Add Mobility support for Rails enums.

As an alternative if it can't be implemented, I think adding a disclaimer/warning in the README:documentation would prevent bad surprises (took me 30 minutes to figure out Mobility was the culprit). It looks now like I need to choose between handling raw integer values or un-translating the attribute.

**Comment by shioyama** [comment]
Hmm I guess I'm biased but I wouldn't expect this to work :laughing: 

I don't know how enums really work but I guess AR defines methods when you call `enum`.

...and, indeed, that's what happens:

https://github.com/shioyama/rails/blob/acee501edd0274acb1b073aac1ac41a3181aafdd/activerecord/lib/active_record/enum.rb#L232-L249
```ruby
          def define_enum_methods(name, value_method_name, value, scopes)
            # def active?() status_for_database == 0 end
            klass.send(:detect_enum_conflict!, name, "#{value_method_name}?")
            define_method("#{value_method_name}?") { public_send(:"#{name}_for_database") == value }

            # def active!() update!(status: 0) end
            klass.send(:detect_enum_conflict!, name, "#{value_method_name}!")
            define_method("#{value_method_name}!") { update!(name => value) }

            # scope :active, -> { where(status: 0) }
            # scope :not_active, -> { where.not(status: 0) }
            if scopes
              klass.send(:detect_enum_conflict!, name, value_method_name, true)
              klass.scope value_method_name, -> { where(name => value) }

              klass.send(:detect_enum_conflict!, name, "not_#{value_method_name}", true)
              klass.scope "not_#{value_method_name}", -> { where.not(name => value) }
            end
          end
```

Oh interesting, and that's in a module builder (`EnumMethods < Module`).

Out of curiosity, what if you call `enum` _before_ you call `translates`? (Also, what backend are you using?)

> adding a disclaimer/warning in the README

I don't really agree about a disclaimer, because if we do that then we're going to need a ton of disclaimers every time Rails has some new magic that conflicts with Mobility.

_Maybe_ what is needed is something stating that any Rails/ActiveRecord magic that defines methods other than the standard attribute methods will likely conflict with Mobility. And/or something explaining that Mobility-defined attributes are not "real" attributes, although Mobility tries to make them as close to that as possible, and that people should not expect them to act that way _unless_ the docs explicitly say they will.

As I said, I'm not surprised this doesn't work (although I would have been pleasantly surprised if it did!)

**Comment by sedubois** [comment]
> Out of curiosity, what if you call enum before you call translates?

Doesn't work either unfortunately.

> Also, what backend are you using?

I'm using the table backend.

So do you think there is no way to make enums translatable with Mobility? AFAIK enums are quite a "staple" of the Rails framework, so I would expect many people could benefit from this 🤔

**Comment by shioyama** [comment]
I'm closing this, this is a compatibility feature which would probably be hard to support. I've had enough headaches supporting dirty tracking.
