### ISSUE TITLE
Use mobility with StoreModel

### ISSUE THREAD

**Issue by 23tux** [shioyama/mobility#591]
## Context
We use the store_model project (https://github.com/DmitryTsepelev/store_model) to define models based on json fields. It would be very useful, to have multi language attributes here.

## Expected Behavior
I tried to write a custom backend for this:

```
class MyBackend
  include Mobility::Backend

  def read(locale, **options)
    # ...
  end

  def write(locale, value, **options)
    # ...
  end

  def each_locale
    # ...
  end
end
```

```
class Configuration
  include StoreModel::Model
  extend Mobility
  
  attribute :name, :json
  translates(:name, backend: MyBackend)
end
```

## Actual Behavior

It seems that mobility is relying on an ActiveRecord::Base class. When I execute the code above, I get this error:

```
     TypeError:
       Dummy should be a subclass of ActiveRecord::Base to use the active_record plugin
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugins/active_record.rb:34:in `block in <module:ActiveRecord>'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:88:in `class_exec'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:88:in `block (2 levels) in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `tap'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
     # /usr/local/bundle/gems/mobility-1.2.9/lib/mobility/plugin.rb:86:in `block in included_hook'
```

Is there a way to use mobility without ActiveRecord? StoreModel uses the ActiveModel attributes API, which seems like a valid use case to me.

**Comment by shioyama** [comment]
First, the error is coming from a `Dummy` class, but I don't know what's in that class. Please provide that to help understand what's going on.

Anyway, assuming you have something like `translates ..., backend: MyBackend`, the problem would be that you have the `active_record` plugin enabled in your configuration, which applies as the default when you call `translates`.

`translates` is actually just some sugar:

https://github.com/shioyama/mobility/blob/c0e429620b2355cd70750f1ea6dc21f667706aac/lib/mobility.rb#L97-L99

So what's actually going on is that you are including an instance of `Mobility.translations_class`, which will default to the translations class with whatever plugins you put in the block passed to `Mobility.configure`. If you have `active_record` in there, then everything is setup for `ActiveRecord::Base` models and won't work for anything else.

But you're in luck! You can easily setup multiple configurations, you just need to create a different translations class like this:

```ruby
class StoreModelTranslations < Mobility::Translations
  backend :my_backend
  reader
  writer

  # whatever other plugins you want for this configuraiton

end
```

Now you can use this alternative configuration with:

```ruby
class Configuration
  include StoreModel::Model

  attribute :name, :json
  include StoreModelTranslations.new(:name)
end
```

I have no idea if this will actually work since I know nothing about StoreModel, but this is the general idea.

**Comment by shioyama** [comment]
This is by the way all documented in inline docs:

https://github.com/shioyama/mobility/blob/c0e429620b2355cd70750f1ea6dc21f667706aac/lib/mobility.rb#L8-L73
