### ISSUE TITLE
Table backend migration generator doesn't actually create a table

### ISSUE THREAD

**Issue by Quintasan** [shioyama/mobility#67]
`rails generate mobility:translations project title:string description:string story:string`

yields

```
class CreateProjectTitleAndDescriptionAndStoryTranslationsForMobilityTableBackend < ActiveRecord::Migration[5.1]
  def change
    add_column :project_translations, :title, :string
    add_column :project_translations, :description, :string
    add_column :project_translations, :story, :string
  end
end
```

Which doesn't work if `project_translations` table doesn't exist beforehand.

This should be either mentioned in the documentation explicitly or the generator should assume there's no such a table and create an appropriate migration.

**Comment by Quintasan** [comment]
Actually scratch that. I passed ``--backend=table` and it worked.

Not sure why I had to do this since I had `:table` set as the backend in the initializer.

**Comment by shioyama** [comment]
It should pick up the backend if you put it in the initializer, so I consider this a bug. I'll look into it, thanks.

**Comment by Quintasan** [comment]
@shioyama I can't reproduce it on a fresh Rails project so I guess I must have made some stupid mistake. Sorry for taking your time.

**Comment by shioyama** [comment]
The only thing that would trigger using the "add columns" template rather than the default "create table" template is the existence of a table `project_translations`, which it checks for [here](https://github.com/shioyama/mobility/blob/4f536011daa7b6c297b09d8337b5f30916d5272f/lib/rails/generators/mobility/backend_generators/table_backend.rb#L10-L10). But I'm not sure why setting the backend explicitly would change the result in that case... anyway, if it works on a fresh project I agree with closing. Let me know if you see it again.
