### ISSUE TITLE
NameError: uninitialized constant Mobility::ActiveRecord::Base

### ISSUE THREAD

**Issue by madis** [shioyama/mobility#69]
When Mobility is loaded for ActiveRecord, it includes `Mobility::ActiveRecord` module https://github.com/shioyama/mobility/blob/b001a2996240ee217ed75c0fb99ed88caae82ed0/lib/mobility.rb#L86

If the `ActiveRecord::Base` subclass that now includes `Mobility` did something like the following before:
```ruby
class MyModel < ActiveRecord::Base
  def my_method
    ActiveRecord::Base.uncached do
      # some code
    end
  end
end
```

It will get an exception raised:
```
NameError:
  uninitialized constant Mobility::ActiveRecord::Base
```

It will get an exception because `ActiveRecord` is found on `Mobility` module first (the original `ActiveRecord` from rails is further down in the _ancestors_ chain.

The fix on the user's side would be to qualify top level lookup with `::ActiveRecord` but I don't know how happy the users of _Mobility_ would be if they had to do it.

Another would be to rename the `ActiveRecord` module in _Mobility_, which would kind of diminish the descriptiveness.

Do you have other suggestions on how to approach this issue?

**Comment by shioyama** [comment]
Wow, nice catch. Never even considered this problem.

There's one easy way to fix it, just extend `Mobility` instead of including it. Then it's not in the ancestors chain of the model, and internally that is what Mobility is doing anyway:

https://github.com/shioyama/mobility/blob/03c9cffc6038e1def19041ec2ea923bebb6522f4/lib/mobility.rb#L98-L100

I think for this, maybe a note in the readme mentioning that both `include` and `extend` will work, but `extend` is preferred for this reason. I should probably change examples to use `extend` too.
