### ISSUE TITLE
Backend decision - use case

### ISSUE THREAD

**Issue by shadowed87** [shioyama/mobility#7]
I am having troubles deciding whether to use :jsonb or :table as backend.
I use Postgres, and I am having the need of keeping 5+ locales.

let's say I want to use :jsonb and the table looks like this (btw. a wiki on the right creation of the migrations would be very useful):
```
create_table :posts do |t|
    t.jsonb :title, null: false, default: '{}'
    t.jsonb :content, null: false, default: '{}'
end
add_index  :posts, :title, using: :gin
add_index  :posts, :content, using: :gin
```

In this case there are two fields that will get two different data. 
The first is a title (max 200 chars), and the second is the content of the post (3000+ chars).

The doubt arise from the fact that rails gets the whole columns (3000+ chars) with all the translations at once from the db ({it: ..., es: ..., en: ..., ...}). 
Even if, in the end, only one of the locale will be used. 

In the case of the title looks ok, while for the content it could be an useless amount of data retrived (imagine 10+ locales). 
I would have preferred to get only the required locale from the db (through something like: SELECT content->':locale' as content) but it's not currently possible with rails. 

Is this a good practice? Is this a case where using :table (or also :key_value) as backend is preferred, even with postgres? Am I missing something or overthinking over a non-problem?

Ps. I am sorry in advance if this is not the appropriate place where discuss about this.

**Comment by shioyama** [comment]
I think this is a really interesting question. You're correct that PostgreSQL jsonb columns may not be the best solution in all situations, since it groups all locales together.

I think the way to think about this is: do you want to deal with all *locales* for a given *attribute* together (jsonb/hstore/serialized), or all *attributes* for a given *locale* together (table) ? The former is more useful if e.g. you have some kind of translation interface, where you want to see translations for a given attribute together; the latter is more useful if you only want to see translations for one locale at a time. The key-value backend breaks translations down to atomic attribute+locale+value sets, which can be grouped either way (but at the cost of increased query complexity).

Also, as you mentioned, PostgreSQL supports fast querying on jsonb columns, but Rails does not support this (yet anyway). Mobility does some [tricky stuff with Arel](https://github.com/shioyama/mobility/blob/c99809afc7c4641ed9aac565200c544b781eb726/lib/mobility/backend/active_record/jsonb/query_methods.rb#L10-L27) to get around this limitation, so as long as you're only querying on values in a locale you can use `i18n.where` and it will handle the magic, but for other stuff it would require more tricky querying. (But having translations on a separate table can require some complex querying as well, let's not forget.)

I'm going to close this because although it's an interesting discussion, it's not really specific to Mobility. The goal of Mobility is to make it so that you can decide which storage strategy to use based solely on the inherent qualities of that strategy, and not on which gem supports it.

That said, I've created a [ruby-i18n](https://groups.google.com/forum/#!forum/ruby-i18n) google group which might be a good place to post the question. Although it's a group of only one person right now - me! - it is public so others might see the question and join in, and I'd be happy to continue discussion over there.
