### ISSUE TITLE
Usage with rails_admin_globalize_field

### ISSUE THREAD

**Issue by Quintasan** [shioyama/mobility#70]
Mobility's `:table` backend is very similar to `globalize`. `globalize` also has [rails_admin_globalize_field](https://github.com/rubyrider/rails_admin_globalize_field) gem which allows easy integration with rails_admin. The only thing that currently doesn't work is setting `accepts_nested_attributes_for :translations, allow_destroy: true` on the model that accepts translation (as instructed in [usage](https://github.com/rubyrider/rails_admin_globalize_field#usage)). When set up, ActiveRecord complains about no association:
```
/home/quintasan/.rvm/gems/ruby-2.4.1@domore/gems/activerecord-5.1.3/lib/active_record/nested_attributes.rb:337:in `block in accepts_nested_attributes_for': No association found for name `translations'. Has it been defined yet? (ArgumentError)
```

Is there any way mobility can set this association when using `:table` backend or is there any way I can fool ActiveRecord into accepting that?

**Comment by shioyama** [comment]
I don't know rails_admin, but the error above is because the table backend by default uses the association name `mobility_model_translations`. I have changed this in the latest version of Mobility (master branch on github) to be the same as Globalize and use just `translations`, so you could just upgrade to the latest version with:

```ruby
gem 'mobility', git: 'https://github.com/shioyama/mobility.git'
```

Alternatively, you can override the association name in your model by passing it as an option:

```ruby
class Post < ApplicationRecord
  include Mobility
  translates :title, association_name: :translations
end
```

That will work in 0.1.x, but you'll need to do it in every model which is kind of a pain.

I'd recommend just using the latest master version of Mobility and let me know if anything breaks for you :wink: I'm planning to release 0.2.0 this weekend or latest sometime next week.

**Comment by Quintasan** [comment]
@shioyama Smashing, I'll try it right away and report back with the results

**Comment by Quintasan** [comment]
@shioyama While this made it work I'm afraid the gem is totally out of sync with Rails. I guess I'll wait for you to finish the base features and work on rails_admin integration later.

**Comment by shioyama** [comment]
Ok that's too bad... I guess I'll close this for now then, if you have any other Mobility-related issues let me know.
