### ISSUE TITLE
Mobility.with_locale(:de) not working in feature specs

### ISSUE THREAD

**Issue by jmuheim** [shioyama/mobility#98]
When I'm doing the following:

```ruby
Mobility.with_locale(:de) do
  visit page_path(@page)
end
```

...then the default locale (en) is still active. It only works like so:

```ruby
visit page_path(@page, locale: :de)
```

**Comment by shioyama** [comment]
This is really a question for SO, but just quickly: `Mobility.locale` is not the same as `I18n.locale`. Setting `Mobility.locale` will take effect for Mobility stuff, but not for stuff that's looking at `I18n.locale` since that locale does not change.

If you want to change the I18n locale, you need to use `I18n.with_locale(:de)`. If `Mobility.locale` is nil, then Mobility will also default to `I18n.locale`.

**Comment by jmuheim** [comment]
You're right, I wasn't aware of this difference. I'm sorry for polluting your issues tracker. Next time I'll ask on SO. 👍

**Comment by jmuheim** [comment]
(Thanks though!)

**Comment by shioyama** [comment]
No worries! The readme could be clearer about this.

**Comment by jmuheim** [comment]
PS: `I18n.with_locale :de { ... }` doesn't seem to work either. Maybe it's running in a different thread or something...?

**Comment by shioyama** [comment]
I think you need `do/end` for that to work.

**Comment by jmuheim** [comment]
I did... I just replaced it with curly braces to make a one-liner here. 😅

**Comment by shioyama** [comment]
hmm not really sure, you mean mobility is not showing translations in German?

**Comment by jmuheim** [comment]
No, the Rails routing mechanism still sent me to the english page.

**Comment by shioyama** [comment]
Well, that's really not a Mobility issue at all...

**Comment by jmuheim** [comment]
Exactly. Just wanted to point it out here for someone else coming from Google or so... 👍
